import { defineConfig } from 'vite';
import monkey from 'vite-plugin-monkey';

export default defineConfig({
  plugins: [
    monkey({
      entry: 'StateFarmClient.js',
      userscript: {
        name: 'Shell Shockers Aimbot & ESP: StateFarm Client V3 - Bloom, Chat, Botting, Unban & More, shellshock.io',
        description: 'Shell Shockers Aimbot & ESP of the highest level. Best shellshock.io menu in 2025 with NO ADS! Many cheats such as Aimbot, PlayerESP, AmmoESP, Chams, Nametags, Join/Leave alerts, Chat Filter Bypass, AntiAFK, FOV Slider, Zooming, Player Stats, Auto Reload, Auto Unban and many more whilst having unsurpassed customisation options such as binding to any key, easily editable color scheme and themes - all on the fly!',
        author: 'Hydroflame521, enbyte, notfood, 1ust, OakSwingZZZ, Seq and de_Neuublue',
        namespace: 'https://github.com/Hydroflame522/StateFarmClient/',
        supportURL: 'https://github.com/Hydroflame522/StateFarmClient/-/issues/',
        license: 'GPL-3.0',
        'run-at': 'document-start',
        icon: 'https://sfc.best/raw/icons/StateFarmClientLogo384px.png',
        version: '3.5.8', // Update this string dynamically when changing versions
        downloadURL: 'https://sfc.best/js/sf.user.js',
        updateURL: 'https://sfc.best/js/sf.meta.js',
        antifeature: [{ type: 'membership', description: 'Joining the discord is required for full usage of the script.' }],
        grant: [
          'GM_setValue',
          'GM_getValue',
          'GM_deleteValue',
          'GM_listValues',
          'GM_info',
          'GM_setClipboard',
          'GM_openInTab',
          'GM.setValue',
          'GM.getValue',
          'GM.deleteValue',
          'GM.listValues',
          'GM.info',
          'GM.setClipboard',
          'GM.openInTab'
        ],
        match: [
          '*://*.shellshock.io/*',
          '*://*.algebra.best/*',
          '*://*.algebra.monster/*',
          '*://*.algebra.vip/*',
          '*://*.biologyclass.club/*',
          '*://*.combateggs.com/*',
          '*://*.deadlyegg.com/*',
          '*://*.deathegg.life/*',
          '*://*.deathegg.world/*',
          '*://*.eggbattle.com/*',
          '*://*.eggboy.club/*',
          '*://*.eggboy.me/*',
          '*://*.eggboy.xyz/*',
          '*://*.eggcombat.com/*',
          '*://*.egg.dance/*',
          '*://*.eggfacts.fun/*',
          '*://*.egggames.best/*',
          '*://*.egghead.institute/*',
          '*://*.eggisthenewblack.com/*',
          '*://*.eggsarecool.com/*',
          '*://*.eggshock.com/*',
          '*://*.eggshock.me/*',
          '*://*.eggshock.net/*',
          '*://*.eggshooter.best/*',
          '*://*.eggshooter.com/*',
          '*://*.eggwarfare.com/*',
          '*://*.eggwars.io/*',
          '*://*.geometry.best/*',
          '*://*.geometry.monster/*',
          '*://*.geometry.pw/*',
          '*://*.geometry.report/*',
          '*://*.hardboiled.life/*',
          '*://*.hardshell.life/*',
          '*://*.humanorganising.org/*',
          '*://*.mathactivity.club/*',
          '*://*.mathactivity.xyz/*',
          '*://*.mathdrills.info/*',
          '*://*.mathdrills.life/*',
          '*://*.mathfun.rocks/*',
          '*://*.mathgames.world/*',
          '*://*.math.international/*',
          '*://*.mathlete.fun/*',
          '*://*.mathlete.pro/*',
          '*://*.overeasy.club/*',
          '*://*.risenegg.com/*',
          '*://*.scrambled.tech/*',
          '*://*.scrambled.today/*',
          '*://*.scrambled.us/*',
          '*://*.scrambled.world/*',
          '*://*.shellgame.me/*',
          '*://*.shellplay.live/*',
          '*://*.shellshockers.best/*',
          '*://*.shellshockers.ca/*',
          '*://*.shellshockers.club/*',
          '*://*.shellshockers.life/*',
          '*://*.shellshockers.site/*',
          '*://*.shellshockers.today/*',
          '*://*.shellshockers.us/*',
          '*://*.shellshockers.website/*',
          '*://*.shellshockers.wiki/*',
          '*://*.shellshockers.world/*',
          '*://*.shellshockers.xyz/*',
          '*://*.shellshock.guru/*',
          '*://*.shellsocks.com/*',
          '*://*.softboiled.club/*',
          '*://*.urbanegger.com/*',
          '*://*.violentegg.club/*',
          '*://*.violentegg.fun/*',
          '*://*.yolk.best/*',
          '*://*.yolk.life/*',
          '*://*.yolk.monster/*',
          '*://*.yolk.rocks/*',
          '*://*.yolk.tech/*',
          '*://*.yolk.quest/*',
          '*://*.yolk.today/*',
          '*://*.zygote.cafe/*'
        ]
      },
      build: {
        externalGlobals: {
          tweakpane: ['tweakpane', 'https://cdn.jsdelivr.net/npm/tweakpane@3.1.10/dist/tweakpane.min.js'],
        },
        fileName: 'StateFarmClient.user.js'
      }
    }),
  ],
});